/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Gangabon__factory } from "./Gangabon__factory";
export { GangabonDMRV__factory } from "./GangabonDMRV__factory";
